// flow-typed signature: 4a2a9e81e8799e898f9cd563567a8acf
// flow-typed version: <<STUB>>/superagent-promise-plugin_v^3.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-promise-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-promise-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-promise-plugin/src/superagent-promise-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-promise-plugin/index' {
  declare module.exports: $Exports<'superagent-promise-plugin'>;
}
declare module 'superagent-promise-plugin/index.js' {
  declare module.exports: $Exports<'superagent-promise-plugin'>;
}
declare module 'superagent-promise-plugin/src/superagent-promise-plugin.js' {
  declare module.exports: $Exports<'superagent-promise-plugin/src/superagent-promise-plugin'>;
}
