// flow-typed signature: 1dc0f778ed6e3ca18507b7cb00066f1d
// flow-typed version: <<STUB>>/tape-watch_v^2.2.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tape-watch/fixtures/othertest' {
  declare module.exports: any;
}

declare module 'tape-watch/lib/mutex' {
  declare module.exports: any;
}

declare module 'tape-watch/lib/wait' {
  declare module.exports: any;
}

declare module 'tape-watch/test/tape' {
  declare module.exports: any;
}

declare module 'tape-watch/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tape-watch/fixtures/othertest.js' {
  declare module.exports: $Exports<'tape-watch/fixtures/othertest'>;
}
declare module 'tape-watch/lib/mutex.js' {
  declare module.exports: $Exports<'tape-watch/lib/mutex'>;
}
declare module 'tape-watch/lib/wait.js' {
  declare module.exports: $Exports<'tape-watch/lib/wait'>;
}
declare module 'tape-watch/test/tape.js' {
  declare module.exports: $Exports<'tape-watch/test/tape'>;
}
declare module 'tape-watch/test/test.js' {
  declare module.exports: $Exports<'tape-watch/test/test'>;
}
